LineLength:
  Description: 'Limit lines to 120 characters.'
  Max: 120
  Enabled: true

Metrics/MethodLength:
  CountComments: false  # count full line comments?
  Max: 100

Metrics/AbcSize:
  Max: 50
